export const agroupations = [
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
];
