export const items = [
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
  'Toothbrush',
  'Razor blade',
  'Ear plugs',
  'Dormidina',
];
