import { Agroupation } from './agroupation';

export const agruoupations2: Agroupation[] = [
  {
    id: 0,
    title: 'Essentials',
    items: [
      'Passport',
      'Smartphone',
      'E-Visa',
      'Boarding pass',
      'DNI',
      'Wallet',
      'Home keys',
      'Cash',
    ],
  },
  {
    id: 0,
    title: 'Job',
    items: [
      'Laptop',
      'Laptop Charger',
      'Iphone',
      'Iphone charger',
      'Notebook',
      'Bag',
      'Headphones',
    ],
  },
  {
    id: 7,
    title: 'Clothes',
    items: [
      'Underwear x 8',
      'Socks x 8',
      'Tshirt/shirt x 8',
      'Long trousers',
      'Jersey',
      'Belt',
      'Sport thsirt',
      'Running shoes',
      'Flip flops',
      'Sport trousers',
      'Waterproof jacket',
      'Swimsuit',
      'Pajamas',
    ],
  },
  {
    id: 0,
    title: 'Makeup bag',
    items: [
      'Toothbrush',
      'Toothpaste',
      'Razor blade',
      'Ear plugs',
      'Mask',
      'Minoxidil',
      'Ferula + pils',
      'Cologne',
      'Deodorant',
      'Glasses case',
      'Eye contacts',
      'Liquid contacts',
      'Nail clippers',
    ],
  },
  {
    id: 2,
    title: 'Electronic stuff',
    items: [
      'Smartphone',
      'Switch',
      'Sony buds',
      'Smartwatch',
      'Kindle',
      'Smartphone Charger',
      'Wire type-C',
      'Wire Iphone',
      'Wire type-old',
      'Wire smartwatch',
    ],
  },
  {
    id: 4,
    title: 'First aid kits',
    items: [
      'Iboprofeno',
      'Couldina',
      'Symbicort',
      'Budesonida',
      'Antiestaminic',
      'Melatonina',
      'Dormidina',
      'Vaporub',
    ],
  },
];

export const agruoupations: Agroupation[] = [
  {
    id: 0,
    title: 'Makeup bag',
    items: ['Toothbrush', 'Toothpaste', 'Razor blade', 'Ear plugs'],
  },
  {
    id: 1,
    title: 'Electronic stuff',
    items: ['Switch', 'Samsung buds', 'Mobile router'],
  },
  {
    id: 2,
    title: 'Leisure',
    items: ['Books', 'SurfSkate', 'Frisbi', 'Hammock'],
  },
  {
    id: 3,
    title: 'First aid kits',
    items: [
      'Iboprofeno',
      'Symbicort',
      'Budesonida',
      'Antiestaminic',
      'Melatonina',
      'Dormidina',
    ],
  },
  {
    id: 4,
    title: 'Electronic stuff',
    items: ['Switch', 'Samsung buds', 'Mobile router'],
  },
  {
    id: 5,
    title: 'Leisure',
    items: ['Books', 'SurfSkate', 'Frisbi', 'Hammock'],
  },
  {
    id: 6,
    title: 'Makeup bag',
    items: ['Toothbrush', 'Razor blade', 'Ear plugs', 'Dormidina'],
  },
  {
    id: 7,
    title: 'Electronic stuff',
    items: ['Switch', 'Samsung buds', 'Mobile router'],
  },
  {
    id: 8,
    title: 'Leisure',
    items: ['Books', 'SurfSkate', 'Frisbi', 'Hammock'],
  },
  {
    id: 9,
    title: 'Makeup bag',
    items: ['Toothbrush', 'Razor blade', 'Ear plugs', 'Dormidina'],
  },
  {
    id: 10,
    title: 'Electronic stuff',
    items: ['Switch', 'Samsung buds', 'Mobile router'],
  },
  {
    id: 11,
    title: 'Leisure',
    items: ['Books', 'SurfSkate', 'Frisbi', 'Hammock'],
  },
  {
    id: 12,
    title: 'Makeup bag',
    items: ['Toothbrush', 'Razor blade', 'Ear plugs', 'Dormidina'],
  },
  {
    id: 13,
    title: 'Electronic stuff',
    items: ['Switch', 'Samsung buds', 'Mobile router'],
  },
  {
    id: 14,
    title: 'Leisure',
    items: ['Books', 'SurfSkate', 'Frisbi', 'Hammock'],
  },
  {
    id: 15,
    title: 'Makeup bag',
    items: ['Toothbrush', 'Razor blade', 'Ear plugs', 'Dormidina'],
  },
  {
    id: 16,
    title: 'Electronic stuff',
    items: ['Switch', 'Samsung buds', 'Mobile router'],
  },
  {
    id: 17,
    title: 'Leisure',
    items: ['Books', 'SurfSkate', 'Frisbi', 'Hammock'],
  },
];
